version: 2
jobs:
  build:
    machine: true
    working_directory: ~/bootleg_phoenix
    steps:
      - checkout
      - run: echo 'export INSTALL_PATH="$HOME/dependencies";export PATH="$INSTALL_PATH/bin:$PATH";export MIX_ENV=test;export VERSION_CIRCLECI=2' >> $BASH_ENV
      - restore_cache:
          key: environment-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "script/ci/prepare.sh" }}-{{ arch }}
      - run:
          name: Install Elixir
          command: script/ci/prepare.sh
      - save_cache:
          key: environment-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "script/ci/prepare.sh" }}-{{ arch }}
          paths:
            - ~/dependencies
      - restore_cache:
          key: dependencies-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "mix.lock" }}-{{ arch }}
      - run:
          name: Preparing dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get;
            mix deps.compile;
            mix dialyzer --plt;
          no_output_timeout: 10m
      - save_cache:
          key: dependencies-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "mix.lock" }}-{{ arch }}
          paths:
            - ~/.mix
            - _build
            - deps
      - run: mix compile
      - run: mix dialyzer
      - run: mix credo --strict
      - run: mix coveralls.html
      - store_test_results:
          path: ~/bootleg_phoenix/_build/test/lib/bootleg_phoenix
      - store_artifacts:
          path: cover
